/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package csdemo;

import java.awt.BorderLayout;
import score.PnlScore;
import student.*;

/**
 *
 * @author DELL
 */
public class FrmMain extends javax.swing.JFrame {
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        //--1 加载PnlStudent面板（学生信息添加面板）
        PnlStudent pnlStudent=new PnlStudent();
        //--2 设置当前窗口的内容面板的布局为边框式布局
        this.getContentPane().setLayout(new BorderLayout());
        //--3 加载学生面板
        this.getContentPane().add(pnlStudent,BorderLayout.CENTER);
        //--4 刷新窗口
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuBar = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        mnuStudent = new javax.swing.JMenu();
        mnuStuAdd = new javax.swing.JMenuItem();
        mnuStuUpdate = new javax.swing.JMenuItem();
        mnuCourse = new javax.swing.JMenu();
        mnuCourseAdd = new javax.swing.JMenuItem();
        mnuCourseUpdate = new javax.swing.JMenuItem();
        mnuScore = new javax.swing.JMenu();
        mnuScoreAdd = new javax.swing.JMenuItem();
        mnuScoreUpdate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("学生成绩管理系统");

        mnuSystem.setText("系统");

        mnuLogout.setText("注销系统");
        mnuSystem.add(mnuLogout);

        mnuBar.add(mnuSystem);

        mnuStudent.setText("学生信息维护");

        mnuStuAdd.setText("学生信息添加");
        mnuStuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStuAddActionPerformed(evt);
            }
        });
        mnuStudent.add(mnuStuAdd);

        mnuStuUpdate.setText("学生信息维护");
        mnuStuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStuUpdateActionPerformed(evt);
            }
        });
        mnuStudent.add(mnuStuUpdate);

        mnuBar.add(mnuStudent);

        mnuCourse.setText("课程信息管理");

        mnuCourseAdd.setText("课程信息添加");
        mnuCourse.add(mnuCourseAdd);

        mnuCourseUpdate.setText("课程信息维护");
        mnuCourse.add(mnuCourseUpdate);

        mnuBar.add(mnuCourse);

        mnuScore.setText("学生成绩管理");

        mnuScoreAdd.setText("学生成绩录入");
        mnuScoreAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuScoreAddActionPerformed(evt);
            }
        });
        mnuScore.add(mnuScoreAdd);

        mnuScoreUpdate.setText("学生成绩管理");
        mnuScore.add(mnuScoreUpdate);

        mnuBar.add(mnuScore);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuStuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStuAddActionPerformed
        //清空当前窗口的内容面板上的所有组件
        this.getContentPane().removeAll();
        //--1 加载PnlStudent面板（学生信息添加面板）
        PnlStudent pnlStudent=new PnlStudent();
        //--2 设置当前窗口的内容面板的布局为边框式布局
        this.getContentPane().setLayout(new BorderLayout());
        //--3 加载学生面板
        this.getContentPane().add(pnlStudent,BorderLayout.CENTER);
        //--4 刷新窗口
        this.validate();
    }//GEN-LAST:event_mnuStuAddActionPerformed

    private void mnuStuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStuUpdateActionPerformed
        //清空当前窗口的内容面板上的所有组件
        this.getContentPane().removeAll();
        //--1 加载PnlStuQuery面板（学生信息维护面板）
        PnlStuQuery pnlStuQuery=new PnlStuQuery();
        //--2 设置当前窗口的内容面板的布局为边框式布局
        this.getContentPane().setLayout(new BorderLayout());
        //--3 加载学生信息维护的面板
        this.getContentPane().add(pnlStuQuery,BorderLayout.CENTER);
        //--4 刷新窗口
        this.validate();
        
    }//GEN-LAST:event_mnuStuUpdateActionPerformed

    private void mnuScoreAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuScoreAddActionPerformed
        //清空当前窗口的内容面板上的所有组件
        this.getContentPane().removeAll();
        //--1 加载PnlScore面板（学生成绩录入面板）
        PnlScore pnlScore=new PnlScore();
        //--2 设置当前窗口的内容面板的布局为边框式布局
        this.getContentPane().setLayout(new BorderLayout());
        //--3 加载学生信息维护的面板
        this.getContentPane().add(pnlScore,BorderLayout.CENTER);
        //--4 刷新窗口
        this.validate();
    }//GEN-LAST:event_mnuScoreAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuCourse;
    private javax.swing.JMenuItem mnuCourseAdd;
    private javax.swing.JMenuItem mnuCourseUpdate;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenu mnuScore;
    private javax.swing.JMenuItem mnuScoreAdd;
    private javax.swing.JMenuItem mnuScoreUpdate;
    private javax.swing.JMenuItem mnuStuAdd;
    private javax.swing.JMenuItem mnuStuUpdate;
    private javax.swing.JMenu mnuStudent;
    private javax.swing.JMenu mnuSystem;
    // End of variables declaration//GEN-END:variables
}
