/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package score;
import csdemo.DBCon;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class PnlScore extends javax.swing.JPanel {
    Vector<Vector> data;
    Vector title;
    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form PnlScore
     */
    public PnlScore() {
        initComponents();
        String sql="Select s.stuId,stuName,c.courseId,courseName,grade,term from Student s,Score g,Course c"
                + " where s.stuId=g.stuId and g.courseId=c.courseId"; 
        data=DBCon.queryData(sql);
        //准备表头
        title=new Vector();
        title.add("学号");
        title.add("学生姓名");
        title.add("课程编号");
        title.add("课程名称");
        title.add("成绩");
        title.add("学期");
        tblScore.setModel(dtm);
        dtm.setDataVector(data, title);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGrade = new javax.swing.JTextField();
        lblTerm = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblUserId = new javax.swing.JLabel();
        lblStuId = new javax.swing.JLabel();
        txtStuId = new javax.swing.JTextField();
        lblCourseId = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        lblStuName1 = new javax.swing.JLabel();
        lblStuName = new javax.swing.JLabel();
        lblCourseName1 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        scp = new javax.swing.JScrollPane();
        tblScore = new javax.swing.JTable();

        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        lblTerm.setText("选课学期");

        btnAdd.setText("录入成绩");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("保存");

        lblStuId.setText("学生学号");

        txtStuId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStuIdKeyPressed(evt);
            }
        });

        lblCourseId.setText("课程编号");

        txtCourseId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCourseIdKeyPressed(evt);
            }
        });

        lblStuName1.setText("学生姓名");

        lblCourseName1.setText("课程名称");

        lblGrade.setText("最终成绩");

        tblScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scp.setViewportView(tblScore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStuName1)
                        .addGap(18, 18, 18)
                        .addComponent(lblStuName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStuId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStuId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTerm)
                        .addGap(18, 18, 18)
                        .addComponent(txtTerm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseId)
                        .addGap(18, 18, 18)
                        .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseName1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scp, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuId)
                    .addComponent(txtStuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseId)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lblStuName1))
                        .addComponent(lblCourseName1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrade)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerm)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scp, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeActionPerformed

    private void txtStuIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStuIdKeyPressed
        if(evt.getKeyCode()==10){//当按下回车键
            //获取输入的学号
             String  stuId=txtStuId.getText();
             String stuName=DBCon.queryName("Student", stuId);
             if(stuName!=null){
                 lblStuName.setText(stuName);
             }
        }
    }//GEN-LAST:event_txtStuIdKeyPressed

    private void txtCourseIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCourseIdKeyPressed
        if(evt.getKeyCode()==10){//当按下回车键
            //获取输入的课程编号
             String courseId=txtCourseId.getText();
             String courseName=DBCon.queryName("Course", courseId);
             if(courseName!=null){
                 lblCourseName.setText(courseName);
             }
        }
    }//GEN-LAST:event_txtCourseIdKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //获得学号、课程编号、成绩和学期
        String stuId=txtStuId.getText();
        String courseId=txtCourseId.getText();
        String score=txtGrade.getText();
        String term=txtTerm.getText();
        
        String sql="insert into Score (stuId,courseId,grade,term) values('"+stuId+"','"+courseId 
                +"',"+score+",'"+term+"')";
        System.out.println(sql);
        if(DBCon.updateData(sql)){
            //刷新数据
            String sql2="Select s.stuId,stuName,c.courseId,courseName,grade,term from Student s,Score g,Course c"
                + " where s.stuId=g.stuId and g.courseId=c.courseId"; 
            data=DBCon.queryData(sql2);
            dtm.setDataVector(data, title);
            JOptionPane.showMessageDialog(null, "录入成绩数据成功","系统信息",JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            JOptionPane.showMessageDialog(null, "录入成绩数据失败","系统信息",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseName1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblStuId;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblStuName1;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JScrollPane scp;
    private javax.swing.JTable tblScore;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtStuId;
    private javax.swing.JTextField txtTerm;
    // End of variables declaration//GEN-END:variables
}
