/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student;
import csdemo.DBCon;
import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author Lenovo
 */
public class PnlStuQuery extends javax.swing.JPanel {
    Vector<Vector> data;
    Vector title;
    DefaultTableModel dtm=new DefaultTableModel();
    String stuId="";
    int row=0;
    /**
     * Creates new form PnlStuQuery
     */
    public PnlStuQuery() {
        initComponents();
        //准备数据
        data=DBCon.queryData("select * from Student");
        //准备表头
        title=new Vector();
        title.add("学号");
        title.add("姓名");
        title.add("性别");
        title.add("生日");
        
        //设置表格模式
        tblStu.setModel(dtm);
        showTableData();
        //让表格中第一行数据选中
        tblStu.setRowSelectionInterval(0, 0);
        //获取第一行的数据
        Vector vStu=(Vector)data.get(row);
        //获取第一行数据学生的学号
        stuId=(String)vStu.get(0);
    }
    
    //在表格中显示数据的方法
    void showTableData(){
        dtm.setDataVector(data, title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSex = new javax.swing.ButtonGroup();
        lblSex = new javax.swing.JLabel();
        radMan = new javax.swing.JRadioButton();
        radWoman = new javax.swing.JRadioButton();
        lblBirth = new javax.swing.JLabel();
        txtBirth = new javax.swing.JTextField();
        scpStu = new javax.swing.JScrollPane();
        tblStu = new javax.swing.JTable();
        txtBirth2 = new javax.swing.JTextField();
        radNull = new javax.swing.JRadioButton();
        txtStuID = new javax.swing.JTextField();
        lblZhi = new javax.swing.JLabel();
        lblStuName = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        txtStuName = new javax.swing.JTextField();
        lblUserId = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        lblSex.setText("性别");

        btngrpSex.add(radMan);
        radMan.setText("男");

        btngrpSex.add(radWoman);
        radWoman.setText("女");

        lblBirth.setText("生日");

        tblStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStuMouseClicked(evt);
            }
        });
        scpStu.setViewportView(tblStu);

        btngrpSex.add(radNull);
        radNull.setText("不限");

        lblZhi.setText("至");

        lblStuName.setText("姓名");

        lblStuID.setText("学号");

        btnQuery.setText("查询");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        btnUpdate.setText("修改");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpStu, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radMan)
                                .addGap(12, 12, 12)
                                .addComponent(radWoman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radNull))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStuID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBirth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZhi)
                                    .addComponent(lblStuName))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBirth2)
                            .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuID)
                    .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStuName)
                    .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(radMan)
                    .addComponent(radWoman)
                    .addComponent(radNull))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirth)
                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZhi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuery)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(scpStu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        //获取输入的查询条件
        String stuId=txtStuID.getText();
        String stuName=txtStuName.getText();
        String sex="";
        if(radMan.isSelected()){
            sex="男";
        }else if(radWoman.isSelected()){
            sex="女";
        }
        String birth1=txtBirth.getText();
        String birth2=txtBirth2.getText();
        
        String sql="Select * from Student where 1=1";
        
        String query="";
        if(stuId.length()>0){
            query="stuId like '%"+stuId+"%'";
        }
        
        if(stuName.length()>0){
            if(query.length()>0){
                query=query+ " and stuName like '%"+stuName+"%'";
            }else{
                query="stuName like '%"+stuName+"%'";
            }
        }
        
        if(sex.length()>0){
            if(query.length()>0){
                query=query+ " and sex='"+sex+"'";
            }else{
                query="sex='"+sex+"'";
            }
        }
        
        String birthQuery="";
        if(birth1.length()>0 && birth2.length()==0){
            birthQuery="birth>='"+birth1+"'";
        }else if(birth1.length()==0 && birth2.length()>0){
            birthQuery="birth<='"+birth2+"'";
        }else if(birth1.length()>0 && birth2.length()>0){
            birthQuery="birth>='"+birth1+"' and birth<='"+birth2+"'";
        }
        
        if(birthQuery.length()>0){
            query=query+" and "+birthQuery;
        }
        
        if(query.length()>0){
            sql=sql+" and "+query;
        }
        System.out.println(sql);
        data=DBCon.queryData(sql);
        showTableData();
    }//GEN-LAST:event_btnQueryActionPerformed

    private void tblStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStuMouseClicked
        //--1 获取表中选中行号的索引
        row=tblStu.getSelectedRow();
        //--2 获得该行学生的学号
        Vector vStu=(Vector)data.get(row);
        stuId=(String)vStu.get(0);
        
        
        
    }//GEN-LAST:event_tblStuMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //打开学生详细信息面板
        //--3 清空面板父类容器(内容面板)的所有组件
        JPanel pnl=(JPanel)this.getParent();
        pnl.removeAll();
        //--4 加载PnlStuDetail面板（学生详细信息面板）
        PnlStuDetail pnlStuDetail=new PnlStuDetail(stuId);
        //--5 设置当前内容面板的布局为边框式布局
        pnl.setLayout(new BorderLayout());
        //--6 加载学生详细信息的面板
        pnl.add(pnlStuDetail,BorderLayout.CENTER);
        //--7 刷新窗口
        pnl.getParent().validate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //确认删除
        if(JOptionPane.showConfirmDialog(null, "你确认要删除该数据吗？","确认删除",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
            String sql="delete from Student where stuId='"+stuId+"'";
            if(DBCon.updateData(sql)){
                //刷新数据
                data=DBCon.queryData("Select * from Student");
                dtm.setDataVector(data, title);
                
                JOptionPane.showMessageDialog(null, "删除数据成功","系统提示",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "删除数据失败","系统提示",JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup btngrpSex;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblZhi;
    private javax.swing.JRadioButton radMan;
    private javax.swing.JRadioButton radNull;
    private javax.swing.JRadioButton radWoman;
    private javax.swing.JScrollPane scpStu;
    private javax.swing.JTable tblStu;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtBirth2;
    private javax.swing.JTextField txtStuID;
    private javax.swing.JTextField txtStuName;
    // End of variables declaration//GEN-END:variables
}
