/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student;
import csdemo.DBCon;
import java.util.*;
import javax.swing.table.DefaultTableModel; //榛樿鐨勮〃鏍兼ā寮�
import javax.swing.*;


/**
 *
 * @author DELL
 */
public class PnlStudent extends javax.swing.JPanel {
    Vector<Vector> data; //数据
    int index=0;
    //实例化默认的表格模式
    DefaultTableModel dtm=new DefaultTableModel();
    Vector title;
    /**
     * Creates new form PnlStudent
     */
    public PnlStudent() {
        initComponents();
        //调用DBCon的方法获取数据
        data=DBCon.queryData("Select * from Student");
        
        //在文本框中显示第一条数据
        showTextData(index);
        radNull.setVisible(false);
        
        //准备表头
        title=new Vector();
        title.add("学号");
        title.add("姓名");
        title.add("性别");
        title.add("生日");
        
        //给表格设置表格模式
        tblStu.setModel(dtm);
        showTableData();
        //表格中第一条数据高亮度显示
        tblStu.setRowSelectionInterval(index, index);
    }
    
    //在表格中显示数据的方法
    void showTableData(){
        dtm.setDataVector(data, title);
    }

    //在文本框中显示数据
    public void showTextData(int index){
        //获取该学生的信息
        Vector stuV=data.get(index);
        //在文本框中显示数据
        txtStuId.setText((String)stuV.get(0));
        txtStuName.setText((String)stuV.get(1));
        String sex=(String)stuV.get(2);
        if(sex.equals("男")){
            radMan.setSelected(true); //男单选按钮选中
        }else{
            radWoman.setSelected(true); //女单选按钮选中
        }
        Object birth=stuV.get(3);
        txtBirth.setText(birth.toString());
        lockText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSex = new javax.swing.ButtonGroup();
        lblUserId = new javax.swing.JLabel();
        pnlDetail = new javax.swing.JPanel();
        lblStuId = new javax.swing.JLabel();
        txtStuId = new javax.swing.JTextField();
        lblStuName = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        txtBirth = new javax.swing.JTextField();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        radMan = new javax.swing.JRadioButton();
        radWoman = new javax.swing.JRadioButton();
        radNull = new javax.swing.JRadioButton();
        scp = new javax.swing.JScrollPane();
        tblStu = new javax.swing.JTable();

        pnlDetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStuId.setText("学号");

        lblStuName.setText("姓名");

        lblSex.setText("性别");

        lblBirth.setText("生日");

        btnPre.setText("<<");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnAdd.setText("添加");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btngrpSex.add(radMan);
        radMan.setText("男");

        btngrpSex.add(radWoman);
        radWoman.setText("女");

        btngrpSex.add(radNull);

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailLayout.createSequentialGroup()
                                .addComponent(lblSex)
                                .addGap(18, 18, 18)
                                .addComponent(radMan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radWoman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radNull))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailLayout.createSequentialGroup()
                                .addComponent(lblStuId)
                                .addGap(18, 18, 18)
                                .addComponent(txtStuId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStuName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetailLayout.createSequentialGroup()
                                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetailLayout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel)))
                        .addGap(0, 186, Short.MAX_VALUE))))
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuId)
                    .addComponent(txtStuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStuName)
                    .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirth)))
                    .addGroup(pnlDetailLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radNull)
                            .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSex)
                                .addComponent(radMan)
                                .addComponent(radWoman)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPre)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        tblStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStuMouseClicked(evt);
            }
        });
        scp.setViewportView(tblStu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        index++;
        if(index>=data.size()){
            index=data.size()-1;
            JOptionPane.showMessageDialog(null, "已经是最后一条记录了","系统信息",JOptionPane.INFORMATION_MESSAGE);
        }
        showTextData(index);
        //表格中高亮度显示数据同步
        tblStu.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        index--;
        if(index<0){
            index=0;
            JOptionPane.showMessageDialog(null, "已经是第一条记录了","系统信息",JOptionPane.INFORMATION_MESSAGE);
        }
        showTextData(index);
        //表格中高亮度显示数据同步
        tblStu.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btnPreActionPerformed

    //锁定文本框的方法
    void lockText(){
        txtStuId.setEnabled(false);
        txtStuName.setEnabled(false);
        txtBirth.setEnabled(false);
        radMan.setEnabled(false);
        radWoman.setEnabled(false);
        btnNext.setEnabled(true);
        btnPre.setEnabled(true);
        btnAdd.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
    }
    //锁定文本框的方法
    void unlockText(){
        txtStuId.setEnabled(true);
        txtStuName.setEnabled(true);
        txtBirth.setEnabled(true);
        radMan.setEnabled(true);
        radWoman.setEnabled(true);
        btnNext.setEnabled(false);
        btnPre.setEnabled(false);
        btnAdd.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
    }
    //清空文本框的方法
    void clearAll(){
        txtStuId.setText("");
        txtStuName.setText("");
        txtBirth.setText("");
        radNull.setSelected(true);
    }
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //解锁
        unlockText();
        //清空
        clearAll();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //获取用户输入的数据
        String stuId=txtStuId.getText();
        String stuName=txtStuName.getText();
        String birth=txtBirth.getText();
        String sex="";
        
        if(radMan.isSelected()){
            sex="男";
        }else if(radWoman.isSelected()){
            sex="女";
        }
        
        //验证输入必填项是否填了
        if(stuId.length()>0 && stuName.length()>0 && sex.length()>0 && birth.length()>0){
            String sql="insert into Student values('"+stuId+"','"+stuName+"','"
                         +sex+"','"+birth+"')";
            //调用DBCon的插入数据的方法来插入数据
            if(DBCon.updateData(sql)){
                //刷新数据
                data=DBCon.queryData("select * from Student");
                showTableData();
                //锁定文本框
                lockText();
                
                JOptionPane.showMessageDialog(null, "添加数据成功","系统信息",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "添加数据失败","系统信息",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //锁定文本框,重新显示数据
        showTextData(index);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStuMouseClicked
        //获取表格上选中的行的索引
        index=tblStu.getSelectedRow();
        showTextData(index);
    }//GEN-LAST:event_tblStuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup btngrpSex;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStuId;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JRadioButton radMan;
    private javax.swing.JRadioButton radNull;
    private javax.swing.JRadioButton radWoman;
    private javax.swing.JScrollPane scp;
    private javax.swing.JTable tblStu;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtStuId;
    private javax.swing.JTextField txtStuName;
    // End of variables declaration//GEN-END:variables
}
